Try setuptools instead of flit
Now `pip -m build` results in this error:

    * Creating venv isolated environment...
    * Installing packages in isolated environment... (setuptools >= 45, setuptools-scm >= 6.2)
    * Getting dependencies for sdist...
    error: Multiple top-level packages discovered in a flat-layout: ['schemas', 'htmlcov', 'sdxdatamodel'].

    To avoid accidental inclusion of unwanted files or directories,
    setuptools will not proceed with this build.

    If you are trying to create a single distribution with multiple packages
    on purpose, you should not rely on automatic discovery.
    Instead, consider the following options:

    1. set up custom discovery (`find` directive with `include` or `exclude`)
    2. use a `src-layout`
    3. explicitly set `py_modules` or `packages` with a list of names

    To find more information, look for "package discovery" on setuptools docs.

    ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist